package me.home.bangumi.dao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.annotation.Index;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bangumiCalendarDaoConfig;
    private final DaoConfig myCollectionDaoConfig;
    private final DaoConfig indexDaoConfig;

    private final BangumiCalendarDao bangumiCalendarDao;
    private final MyCollectionDao myCollectionDao;
    private final IndexDao indexDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bangumiCalendarDaoConfig = daoConfigMap.get(BangumiCalendarDao.class).clone();
        bangumiCalendarDaoConfig.initIdentityScope(type);

        myCollectionDaoConfig = daoConfigMap.get(MyCollectionDao.class).clone();
        myCollectionDaoConfig.initIdentityScope(type);

        indexDaoConfig = daoConfigMap.get(IndexDao.class).clone();
        indexDaoConfig.initIdentityScope(type);

        bangumiCalendarDao = new BangumiCalendarDao(bangumiCalendarDaoConfig, this);
        myCollectionDao = new MyCollectionDao(myCollectionDaoConfig, this);
        indexDao = new IndexDao(indexDaoConfig, this);

        registerDao(BangumiCalendar.class, bangumiCalendarDao);
        registerDao(MyCollection.class, myCollectionDao);
        registerDao(me.home.bangumi.dao.Index.class, indexDao);
    }
    
    public void clear() {
        bangumiCalendarDaoConfig.getIdentityScope().clear();
        myCollectionDaoConfig.getIdentityScope().clear();
        indexDaoConfig.getIdentityScope().clear();
    }

    public BangumiCalendarDao getBangumiCalendarDao() {
        return bangumiCalendarDao;
    }

    public MyCollectionDao getMyCollectionDao() {
        return myCollectionDao;
    }

    public IndexDao getIndexDao() {
        return indexDao;
    }
}
